In [4]:
import pandas as pd
from sklearn.model_selection import KFold
from sklearn.model_selection import cross_val_score
from sklearn.ensemble import RandomForestClassifier
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.metrics import confusion_matrix

In [5]:
from google.colab import files
uploaded=files.upload()

Saving Fraud_check (1).csv to Fraud_check (1).csv


In [6]:
data=pd.read_csv("Fraud_check (1).csv")

In [7]:
data

Undergrad Marital.Status  Taxable.Income  City.Population  \
0          NO         Single           68833            50047   
1         YES       Divorced           33700           134075   
2          NO        Married           36925           160205   
3         YES         Single           50190           193264   
4          NO        Married           81002            27533   
..        ...            ...             ...              ...   
595       YES       Divorced           76340            39492   
596       YES       Divorced           69967            55369   
597        NO       Divorced           47334           154058   
598       YES        Married           98592           180083   
599        NO       Divorced           96519           158137   

     Work.Experience Urban  
0                 10   YES  
1                 18   YES  
2                 30   YES  
3                 15   YES  
4                 28    NO  
..               ...   ...  
595                7   YES  
596                2   YES  
597                0   YES  
598               17    NO  
599               16    NO  

[600 rows x 6 columns]

In [8]:
data.head()

Undergrad Marital.Status  Taxable.Income  City.Population  Work.Experience  \
0        NO         Single           68833            50047               10   
1       YES       Divorced           33700           134075               18   
2        NO        Married           36925           160205               30   
3       YES         Single           50190           193264               15   
4        NO        Married           81002            27533               28   

  Urban  
0   YES  
1   YES  
2   YES  
3   YES  
4    NO

In [9]:
data = pd.get_dummies(data, columns = ['Undergrad','Marital.Status','Urban'])

In [10]:
data.head()

Taxable.Income  City.Population  Work.Experience  Undergrad_NO  \
0           68833            50047               10             1   
1           33700           134075               18             0   
2           36925           160205               30             1   
3           50190           193264               15             0   
4           81002            27533               28             1   

   Undergrad_YES  Marital.Status_Divorced  Marital.Status_Married  \
0              0                        0                       0   
1              1                        1                       0   
2              0                        0                       1   
3              1                        0                       0   
4              0                        0                       1   

   Marital.Status_Single  Urban_NO  Urban_YES  
0                      1         0          1  
1                      0         0          1  
2                      0         0          1  
3                      1         0          1  
4                      0         1          0

In [11]:
data["TaxableIncome"]="good"
data.loc[data["Taxable.Income"]<= 30000,"TaxableIncome"]="risk"
data.drop(["Taxable.Income"],axis=1,inplace=True)

In [12]:
array=data.values
data.head()

City.Population  Work.Experience  Undergrad_NO  Undergrad_YES  \
0            50047               10             1              0   
1           134075               18             0              1   
2           160205               30             1              0   
3           193264               15             0              1   
4            27533               28             1              0   

   Marital.Status_Divorced  Marital.Status_Married  Marital.Status_Single  \
0                        0                       0                      1   
1                        1                       0                      0   
2                        0                       1                      0   
3                        0                       0                      1   
4                        0                       1                      0   

   Urban_NO  Urban_YES TaxableIncome  
0         0          1          good  
1         0          1          good  
2         0          1          good  
3         0          1          good  
4         1          0          good

In [13]:
x = array[:,0:9]
y = array[:,9]

#Spliting the data

In [14]:
x_train,x_test,y_train,y_test = train_test_split(x,y,test_size = 0.2, stratify = y)

#Applying Random forest

In [15]:
num_trees = 100
max_features = 3
kfold = KFold(n_splits=10)
model = RandomForestClassifier(n_estimators=num_trees, max_features=max_features)
model.fit(x_train,y_train)
pred=model.predict(x_test)
acc = accuracy_score(y_test, pred) * 100
print("Accuracy =", acc)
confusion_matrix(y_test, pred)

Accuracy = 75.83333333333333


array([[90,  5],
       [24,  1]])

In [16]:
results = cross_val_score(model, x,y, cv=kfold)
results

array([0.75      , 0.71666667, 0.66666667, 0.66666667, 0.73333333,
       0.66666667, 0.85      , 0.68333333, 0.76666667, 0.81666667])

In [17]:
pred=model.predict(x_test)

In [18]:
pred

array(['risk', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'risk',
       'good', 'good', 'good', 'good', 'risk', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'risk', 'good', 'good',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'risk',
       'good', 'good', 'good', 'good', 'good', 'good', 'good', 'good',
      

#Actual value and Predicted value

In [19]:
df=pd.DataFrame({"actual":y_test,"predicted":pred})
df

actual predicted
0     good      risk
1     good      good
2     risk      good
3     good      good
4     good      good
..     ...       ...
115   good      good
116   risk      good
117   good      good
118   good      risk
119   good      good

[120 rows x 2 columns]

In [20]:
column=data.columns
column

Index(['City.Population', 'Work.Experience', 'Undergrad_NO', 'Undergrad_YES',
       'Marital.Status_Divorced', 'Marital.Status_Married',
       'Marital.Status_Single', 'Urban_NO', 'Urban_YES', 'TaxableIncome'],
      dtype='object')

In [21]:
column=column.drop("TaxableIncome")

#Feature importance

In [22]:
feature=model.feature_importances_
feature

array([0.52217553, 0.35582562, 0.0186019 , 0.01765071, 0.0178076 ,
       0.02025203, 0.01505897, 0.01609528, 0.01653237])

In [23]:
#City population has high importance
df1=pd.DataFrame({"column":column,"importance":feature})
df1.sort_values("importance",ascending=False)

column  importance
0          City.Population    0.522176
1          Work.Experience    0.355826
5   Marital.Status_Married    0.020252
2             Undergrad_NO    0.018602
4  Marital.Status_Divorced    0.017808
3            Undergrad_YES    0.017651
8                Urban_YES    0.016532
7                 Urban_NO    0.016095
6    Marital.Status_Single    0.015059